jobs:
  setup:
    executor: heroku/default
    steps:
        - checkout
        - heroku/install
        - heroku/check-authentication
  build:
    executor: docker/docker
    steps:
        - setup_remote_docker
        - checkout
        - docker/check
        - command: |
          if [[ $(command -v heroku) == "" ]]; then
            curl https://cli-assets.heroku.com/install.sh | sh
          else
            echo "Heroku is already installed. No operation was performed."
          fi
        - run: heroku:login
        - run: docker push registry.heroku.com/$DOCKER_LOGIN/$CIRCLE_PROJECT_REPONAME/web
        - run: heroku container:release -a docker-hy-github-io-my web
        - run: echo "Docker image is " 
        - run: docker images
        - run: echo "fin." 

orbs:
  heroku: circleci/heroku@1.2.3
  docker: circleci/docker@1.0.0
version: 2.1
workflows:
  build-and-deploy:
    jobs:
      - setup
      - build
