jobs:
  build:
    executor: docker/docker
    steps:
        - setup_remote_docker
        - checkout
        - docker/check
        - docker/build:
            image: $DOCKER_LOGIN/$CIRCLE_PROJECT_REPONAME
        - docker/push:
            digest-path: /tmp/digest.txt
            image: $DOCKER_LOGIN/$CIRCLE_PROJECT_REPONAME
        - run:
            command: |
                echo "Digest is: $(</tmp/digest.txt)"
  deploy:
    executor: heroku/default
    steps:
        - checkout
        - heroku/install
        - heroku/push-docker-image
        - heroku/release-docker-image
orbs:
  heroku: circleci/heroku@1.2.3
  docker: circleci/docker@1.0.0
version: 2.1
workflows:
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: sequential-branch-filter
